# Generated by Django 5.2 on 2026-01-17 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'color', 'verbose_name_plural': 'colors'},
        ),
    ]
